"""
llm.py
------
Wraps the Google Gemini 2.5 Flash model behind a small, testable interface.

Provides both a synchronous full-response call and a streaming generator,
used respectively by non-streaming API consumers and the FastAPI streaming
endpoint that Streamlit reads token-by-token.
"""

from __future__ import annotations

from typing import Iterator, List, Optional

from backend.config import get_settings
from backend.prompts import SYSTEM_PROMPT
from backend.utils import get_logger

logger = get_logger(__name__)


class GeminiClient:
    """Thin wrapper around google-generativeai's Gemini chat model."""

    def __init__(self) -> None:
        import google.generativeai as genai  # local import: heavy/optional dep

        settings = get_settings()
        if not settings.gemini_api_key:
            logger.warning(
                "GEMINI_API_KEY is not set. Set it in your .env file before "
                "making live requests."
            )
        genai.configure(api_key=settings.gemini_api_key)
        self._genai = genai
        self._settings = settings
        self._model = genai.GenerativeModel(
            model_name=settings.gemini_model,
            system_instruction=SYSTEM_PROMPT,
        )

    def generate(self, prompt: str) -> str:
        """Generate a full (non-streaming) response for the given prompt.

        Args:
            prompt: The fully assembled user-turn prompt (context + question).

        Returns:
            The model's response text.

        Raises:
            RuntimeError: If the Gemini API call fails.
        """
        try:
            response = self._model.generate_content(
                prompt,
                generation_config=self._genai.types.GenerationConfig(
                    temperature=self._settings.llm_temperature,
                    max_output_tokens=self._settings.llm_max_output_tokens,
                ),
            )
            return response.text
        except Exception as exc:  # noqa: BLE001
            logger.exception("Gemini generate_content failed")
            raise RuntimeError(f"LLM generation failed: {exc}") from exc

    def stream(self, prompt: str) -> Iterator[str]:
        """Stream a response for the given prompt, yielding text deltas.

        Args:
            prompt: The fully assembled user-turn prompt (context + question).

        Yields:
            Successive text chunks as they are generated by Gemini.

        Raises:
            RuntimeError: If the Gemini API call fails.
        """
        try:
            response = self._model.generate_content(
                prompt,
                generation_config=self._genai.types.GenerationConfig(
                    temperature=self._settings.llm_temperature,
                    max_output_tokens=self._settings.llm_max_output_tokens,
                ),
                stream=True,
            )
            for chunk in response:
                if chunk.text:
                    yield chunk.text
        except Exception as exc:  # noqa: BLE001
            logger.exception("Gemini streaming generate_content failed")
            raise RuntimeError(f"LLM streaming failed: {exc}") from exc


_client: Optional[GeminiClient] = None


def get_llm_client() -> GeminiClient:
    """Return a process-wide singleton GeminiClient instance."""
    global _client
    if _client is None:
        _client = GeminiClient()
    return _client
